name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Build applications
      run: |
        npm run install-all
        npm run build
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/ayuradhi
          git pull origin main
          pm2 delete all || true
          
          cd backend
          npm install --production
          pm2 start server.js --name "api"
          
          cd ../frontend
          npm install
          npm run build
          pm2 serve build 3001 --name "frontend" --spa
          
          cd ../admin
          npm install
          npm run build
          pm2 serve build 3000 --name "admin" --spa
          
          pm2 save